# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/home.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1284, 692)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(100, 0, 1280, 692))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page_3)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1281, 701))
        self.label_4.setStyleSheet("background-color: rgb(0,0,0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.txt_name = QtWidgets.QLineEdit(parent=self.page_3)
        self.txt_name.setGeometry(QtCore.QRect(450, 150, 321, 51))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_name.setFont(font)
        self.txt_name.setAutoFillBackground(False)
        self.txt_name.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.txt_password = QtWidgets.QLineEdit(parent=self.page_3)
        self.txt_password.setGeometry(QtCore.QRect(450, 290, 321, 51))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_password.setFont(font)
        self.txt_password.setAutoFillBackground(False)
        self.txt_password.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.txt_password.setText("")
        self.txt_password.setObjectName("txt_password")
        self.txt_email = QtWidgets.QLineEdit(parent=self.page_3)
        self.txt_email.setGeometry(QtCore.QRect(450, 220, 321, 51))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_email.setFont(font)
        self.txt_email.setAutoFillBackground(False)
        self.txt_email.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.txt_email.setText("")
        self.txt_email.setReadOnly(True)
        self.txt_email.setObjectName("txt_email")
        self.txt_nationality = QtWidgets.QLineEdit(parent=self.page_3)
        self.txt_nationality.setGeometry(QtCore.QRect(450, 360, 321, 51))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_nationality.setFont(font)
        self.txt_nationality.setAutoFillBackground(False)
        self.txt_nationality.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.txt_nationality.setText("")
        self.txt_nationality.setObjectName("txt_nationality")
        self.txt_age = QtWidgets.QLineEdit(parent=self.page_3)
        self.txt_age.setGeometry(QtCore.QRect(450, 430, 321, 51))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_age.setFont(font)
        self.txt_age.setAutoFillBackground(False)
        self.txt_age.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.txt_age.setText("")
        self.txt_age.setObjectName("txt_age")
        self.btn_save = QtWidgets.QPushButton(parent=self.page_3)
        self.btn_save.setGeometry(QtCore.QRect(510, 560, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton#btn_save{\n"
"    color: rgb(255,255,255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#btn_save:hover{\n"
"}\n"
"QPushButton#btn_save:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"font: 700 50pt \"Segoe UI\";")
        self.btn_save.setObjectName("btn_save")
        self.avatar_btn = QtWidgets.QPushButton(parent=self.page_3)
        self.avatar_btn.setEnabled(True)
        self.avatar_btn.setGeometry(QtCore.QRect(550, 20, 121, 121))
        self.avatar_btn.setStyleSheet("background-color: rgb(144,0,0);")
        self.avatar_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/user1_white_border.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.avatar_btn.setIcon(icon)
        self.avatar_btn.setIconSize(QtCore.QSize(100, 100))
        self.avatar_btn.setAutoRepeat(False)
        self.avatar_btn.setAutoExclusive(False)
        self.avatar_btn.setAutoDefault(False)
        self.avatar_btn.setDefault(False)
        self.avatar_btn.setFlat(True)
        self.avatar_btn.setObjectName("avatar_btn")
        self.cb_gender = QtWidgets.QComboBox(parent=self.page_3)
        self.cb_gender.setGeometry(QtCore.QRect(450, 500, 321, 51))
        self.cb_gender.setAcceptDrops(False)
        self.cb_gender.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"border-bottom: 2px solid rgb(255,255,255); color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.cb_gender.setObjectName("cb_gender")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.cb_gender.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(parent=self.page_4)
        self.label_5.setGeometry(QtCore.QRect(-50, -10, 1280, 711))
        self.label_5.setStyleSheet("background-color: rgb(0,0,0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.lbl_detail_image = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_image.setGeometry(QtCore.QRect(50, 80, 301, 431))
        self.lbl_detail_image.setStyleSheet("border: 2px solid white;\n"
"border-radius: 5px;")
        self.lbl_detail_image.setText("")
        self.lbl_detail_image.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/sponge.jpg"))
        self.lbl_detail_image.setObjectName("lbl_detail_image")
        self.btn_play_video = QtWidgets.QPushButton(parent=self.page_4)
        self.btn_play_video.setGeometry(QtCore.QRect(120, 520, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.btn_play_video.setFont(font)
        self.btn_play_video.setStyleSheet("QPushButton#btn_watch1{\n"
"    color: rgb(255,255,255);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#btn_watch1:hover{\n"
"}\n"
"QPushButton#btn_watch1:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(105, 118, 132, 255);\n"
"}\n"
"font: 700 50pt \"Segoe UI\";")
        self.btn_play_video.setObjectName("btn_play_video")
        self.lbl_detail_name = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_name.setGeometry(QtCore.QRect(370, 80, 661, 41))
        self.lbl_detail_name.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_name.setObjectName("lbl_detail_name")
        self.lbl_detail_type = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_type.setGeometry(QtCore.QRect(370, 140, 661, 41))
        self.lbl_detail_type.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_type.setObjectName("lbl_detail_type")
        self.lbl_detail_country = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_country.setGeometry(QtCore.QRect(370, 190, 661, 41))
        self.lbl_detail_country.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_country.setObjectName("lbl_detail_country")
        self.lbl_detail_duration = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_duration.setGeometry(QtCore.QRect(370, 250, 661, 41))
        self.lbl_detail_duration.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_duration.setObjectName("lbl_detail_duration")
        self.lbl_detail_release_date = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_release_date.setGeometry(QtCore.QRect(370, 310, 661, 41))
        self.lbl_detail_release_date.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_release_date.setObjectName("lbl_detail_release_date")
        self.lbl_detail_description = QtWidgets.QLabel(parent=self.page_4)
        self.lbl_detail_description.setGeometry(QtCore.QRect(370, 360, 801, 151))
        self.lbl_detail_description.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.lbl_detail_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_detail_description.setObjectName("lbl_detail_description")
        self.label_5.raise_()
        self.btn_play_video.raise_()
        self.lbl_detail_image.raise_()
        self.lbl_detail_name.raise_()
        self.lbl_detail_type.raise_()
        self.lbl_detail_country.raise_()
        self.lbl_detail_duration.raise_()
        self.lbl_detail_release_date.raise_()
        self.lbl_detail_description.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_6 = QtWidgets.QLabel(parent=self.page_5)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 1191, 701))
        self.label_6.setStyleSheet("background-color: rgb(0,0,0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.search_bar = QtWidgets.QLineEdit(parent=self.page_5)
        self.search_bar.setGeometry(QtCore.QRect(300, 10, 571, 51))
        self.search_bar.setStyleSheet("font: 15pt \"VNAvant\";\n"
"border-radius:20px;")
        self.search_bar.setFrame(True)
        self.search_bar.setObjectName("search_bar")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.page_5)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1164, 0, 20, 691))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.movieList = QtWidgets.QScrollArea(parent=self.page_5)
        self.movieList.setGeometry(QtCore.QRect(50, 70, 1071, 591))
        self.movieList.setWidgetResizable(True)
        self.movieList.setObjectName("movieList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1069, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.movieList.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_5)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 1301, 701))
        self.label_7.setStyleSheet("background-color: rgb(0,0,0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.durationBar = QtWidgets.QSlider(parent=self.page)
        self.durationBar.setGeometry(QtCore.QRect(160, 562, 991, 22))
        self.durationBar.setStyleSheet("/* Progress Bar */\n"
".progress-bar {\n"
"  height: 6px;\n"
"  background: linear-gradient(to right, #4caf50, #8bc34a);\n"
"  border-radius: 5px;\n"
"  position: relative;\n"
"}\n"
"\n"
".progress-bar::-webkit-slider-thumb {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  background: #4caf50;\n"
"  border-radius: 50%;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Volume Bar */\n"
".volume-bar {\n"
"  height: 6px;\n"
"  background: linear-gradient(to right, #2196f3, #03a9f4);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
".volume-bar::-webkit-slider-thumb {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  background: #2196f3;\n"
"  border-radius: 50%;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Add hover effect */\n"
".progress-bar:hover, .volume-bar:hover {\n"
"  opacity: 0.9;\n"
"}\n"
"")
        self.durationBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.durationBar.setObjectName("durationBar")
        self.volumeBar = QtWidgets.QSlider(parent=self.page)
        self.volumeBar.setGeometry(QtCore.QRect(990, 600, 160, 22))
        self.volumeBar.setStyleSheet("/* Progress Bar */\n"
".progress-bar {\n"
"  height: 6px;\n"
"  background: linear-gradient(to right, #4caf50, #8bc34a);\n"
"  border-radius: 5px;\n"
"  position: relative;\n"
"}\n"
"\n"
".progress-bar::-webkit-slider-thumb {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  background: #4caf50;\n"
"  border-radius: 50%;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Volume Bar */\n"
".volume-bar {\n"
"  height: 6px;\n"
"  background: linear-gradient(to right, #2196f3, #03a9f4);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
".volume-bar::-webkit-slider-thumb {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  background: #2196f3;\n"
"  border-radius: 50%;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"/* Add hover effect */\n"
".progress-bar:hover, .volume-bar:hover {\n"
"  opacity: 0.9;\n"
"}\n"
"")
        self.volumeBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeBar.setObjectName("volumeBar")
        self.playBtn = QtWidgets.QPushButton(parent=self.page)
        self.playBtn.setGeometry(QtCore.QRect(630, 600, 31, 29))
        self.playBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/play-button-white-on-black.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playBtn.setIcon(icon1)
        self.playBtn.setFlat(True)
        self.playBtn.setObjectName("playBtn")
        self.volumeBtn = QtWidgets.QPushButton(parent=self.page)
        self.volumeBtn.setGeometry(QtCore.QRect(940, 590, 41, 41))
        self.volumeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/volume-up-white-on-black.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.volumeBtn.setIcon(icon2)
        self.volumeBtn.setIconSize(QtCore.QSize(25, 25))
        self.volumeBtn.setFlat(True)
        self.volumeBtn.setObjectName("volumeBtn")
        self.videoWidget = QtWidgets.QWidget(parent=self.page)
        self.videoWidget.setGeometry(QtCore.QRect(10, 60, 1161, 491))
        self.videoWidget.setObjectName("videoWidget")
        self.timeLabel = QtWidgets.QLabel(parent=self.page)
        self.timeLabel.setGeometry(QtCore.QRect(50, 560, 101, 31))
        self.timeLabel.setStyleSheet("font: 10pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.timeLabel.setObjectName("timeLabel")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 331, 31))
        self.label_2.setStyleSheet("font: 700 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgb(255,255,255);\n"
"padding-bottom:7px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 101, 701))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_account = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_account.setEnabled(True)
        self.btn_account.setGeometry(QtCore.QRect(0, 0, 101, 101))
        self.btn_account.setStyleSheet("background-color: rgb(144,0,0);")
        self.btn_account.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/user1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_account.setIcon(icon3)
        self.btn_account.setIconSize(QtCore.QSize(75, 75))
        self.btn_account.setAutoRepeat(False)
        self.btn_account.setAutoExclusive(False)
        self.btn_account.setAutoDefault(False)
        self.btn_account.setDefault(False)
        self.btn_account.setFlat(True)
        self.btn_account.setObjectName("btn_account")
        self.btn_home = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_home.setEnabled(True)
        self.btn_home.setGeometry(QtCore.QRect(0, 100, 101, 101))
        self.btn_home.setStyleSheet("background-color: rgb(144,0,0);")
        self.btn_home.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/home1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon4)
        self.btn_home.setIconSize(QtCore.QSize(50, 50))
        self.btn_home.setAutoRepeat(False)
        self.btn_home.setAutoExclusive(False)
        self.btn_home.setAutoDefault(False)
        self.btn_home.setDefault(False)
        self.btn_home.setFlat(True)
        self.btn_home.setObjectName("btn_home")
        self.btn_saved = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_saved.setEnabled(True)
        self.btn_saved.setGeometry(QtCore.QRect(0, 200, 101, 101))
        self.btn_saved.setStyleSheet("background-color: rgb(144,0,0);")
        self.btn_saved.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/bookmark-white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_saved.setIcon(icon5)
        self.btn_saved.setIconSize(QtCore.QSize(50, 50))
        self.btn_saved.setAutoRepeat(False)
        self.btn_saved.setAutoExclusive(False)
        self.btn_saved.setAutoDefault(False)
        self.btn_saved.setDefault(False)
        self.btn_saved.setFlat(True)
        self.btn_saved.setObjectName("btn_saved")
        self.btn_watch = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_watch.setEnabled(True)
        self.btn_watch.setGeometry(QtCore.QRect(0, 300, 101, 101))
        self.btn_watch.setStyleSheet("background-color: rgb(144,0,0);")
        self.btn_watch.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTI/HTLO-PTI03/PTI_VinhPhat_HaoNan/ui/../img/camera.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_watch.setIcon(icon6)
        self.btn_watch.setIconSize(QtCore.QSize(60, 60))
        self.btn_watch.setAutoRepeat(False)
        self.btn_watch.setAutoExclusive(False)
        self.btn_watch.setAutoDefault(False)
        self.btn_watch.setDefault(False)
        self.btn_watch.setFlat(True)
        self.btn_watch.setObjectName("btn_watch")
        self.txt_name_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_name_5.setGeometry(QtCore.QRect(570, 770, 351, 71))
        font = QtGui.QFont()
        font.setFamily("antipasto")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.txt_name_5.setFont(font)
        self.txt_name_5.setAutoFillBackground(False)
        self.txt_name_5.setStyleSheet("font: 15pt \"antipasto\";\n"
"background-color:rgba(0, 0, 0, 0); border:none;\n"
"color:rgba(0, 99, 177, 230);\n"
"padding-bottom:7px;\n"
"")
        self.txt_name_5.setObjectName("txt_name_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Username"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.txt_nationality.setPlaceholderText(_translate("MainWindow", "Nationality"))
        self.txt_age.setPlaceholderText(_translate("MainWindow", "Age"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.cb_gender.setItemText(0, _translate("MainWindow", "Male"))
        self.cb_gender.setItemText(1, _translate("MainWindow", "Female"))
        self.cb_gender.setItemText(2, _translate("MainWindow", "Other"))
        self.btn_play_video.setText(_translate("MainWindow", "Xem phim"))
        self.lbl_detail_name.setText(_translate("MainWindow", "Tên phim:"))
        self.lbl_detail_type.setText(_translate("MainWindow", "Thể loại:"))
        self.lbl_detail_country.setText(_translate("MainWindow", "Quốc gia:"))
        self.lbl_detail_duration.setText(_translate("MainWindow", "Thời lượng:"))
        self.lbl_detail_release_date.setText(_translate("MainWindow", "Ngày phát hành:"))
        self.lbl_detail_description.setText(_translate("MainWindow", "Mô tả:"))
        self.search_bar.setPlaceholderText(_translate("MainWindow", "  ⌕Search"))
        self.timeLabel.setText(_translate("MainWindow", "00:00:00 00:00:00"))
        self.label_2.setText(_translate("MainWindow", "Tiêu đề phim"))
        self.txt_name_5.setText(_translate("MainWindow", "Những Mảnh Ghép Cảm Xúc 2 "))
        self.txt_name_5.setPlaceholderText(_translate("MainWindow", "Username"))
